### ISSUE TITLE
CI: Publish workflow: Require non-empty changelog, add flags, and announce on Slack

### ISSUE THREAD

**Issue by bisgardo** [Concordium/concordium-dapp-libraries#56]
It doesn't make sense to make a release without any changes worth mentioning. We should therefore require that the extracted change isn't empty and have the workflow verify this.

In the (unforseen) case that the message in the annotated tag is in fact sufficient, we might add a boolean input flag to either allow the changelog to be empty or not attempt to extract it at all. Either way, the "Changelog" section of the release notes should be included only if it's followed by any entries.

We might also want to add flags for skipping other actions like publishing to npm or GitHub. But more likely we should split the workflow such that the current one only publishes to GitHub. Publishing to npm will happen in a separate workflow which is triggered automatically by a publish to GitHub. This allows the possibility of manual GitHub releases to automatically sync to the npm registry.

It would also be neat if a message announcing the release was automatically posted to the appropriate Slack channel.

This task is a followup to https://github.com/Concordium/concordium-dapp-libraries/pull/39.

**Comment by limemloh** [comment]
We decided not to do this, since this has never been an issue and we plan to move away extracting the changelog
